// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAYenIQ8Lc65pZ2u5Lx-GObdzxABJFhMk',
    appId: '1:905201177174:web:e489e4d82f56ddfa02a1f7',
    messagingSenderId: '905201177174',
    projectId: 'instagram-clone-ab4c0',
    authDomain: 'instagram-clone-ab4c0.firebaseapp.com',
    storageBucket: 'instagram-clone-ab4c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyK2Txrev9ID104xzadOxeuF4KvhGhbtU',
    appId: '1:905201177174:android:55d33d90837f227202a1f7',
    messagingSenderId: '905201177174',
    projectId: 'instagram-clone-ab4c0',
    storageBucket: 'instagram-clone-ab4c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqa-bYHtJmU61Y9P7pM6JxH6XRYOzr5k',
    appId: '1:905201177174:ios:818d29538f12c35c02a1f7',
    messagingSenderId: '905201177174',
    projectId: 'instagram-clone-ab4c0',
    storageBucket: 'instagram-clone-ab4c0.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
